### ISSUE TITLE
Meetings/discussion

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/field_lab_q10#13]
Aug 3, 2021
JZ, VLB, SF, TPC, KFP

- different models for calculating Q10
   - reprocess all data using the same function?
   - recalculate using different functions and compare, see which one works best 
- there may be some methane oxidation in field measurements. extra layer of complexity, for interpreting Q10.
- temp range: good
- moisture: is a mess
   - can we normalize the different moisture data types?
   - decoupling temp/moisture is wise
   - SRDB is gravimetric or volumetric
   - get data from global database? historical moisture? compare historical vs. point  during Q10 measurement 
- **ask for extension, Nov 30**

**Comment by jianqiuz** [comment]
Temperature sensitivity functions used in different soil carbon models (Table 3)
https://bg.copernicus.org/articles/13/3735/2016/

**Comment by kaizadp** [comment]
Aug 12, 2021
BBL, JZ, KFP

- moisture content?
   - big questions/flags: are any of the soils under drought or saturation?
   - maybe don't split the middle
- arctic soils incubations done < 0, 0-5 C. JZ will send synthesis papers
   - JZ has incubation data
   - https://onlinelibrary.wiley.com/doi/full/10.1111/gcb.12875. If needed, we could reach out to C. Treat and ask for data used in this synthesis. 

- compute Q10 for model comparison/fit: COSORE, SIDB 
   - if we plot the curve, they mostly deviate at the extremes. lots of divergence around 0 C. identify these extremes and pull more data
   - may not be very different at middle temperatures 
   - Fang and Moncrieff, Lloyd and Taylor

- scope/timeline
   - a comparison of field and lab Q10
   - how well do the different Q10 functions work for the field and lab data?


- next steps
    - KP will pull data from SIDB and COSORE
    - work with JZ to fit the models. get model output, parameters, p-value, R2, etc.
    - time scale for 
    - broom package in R
    - **early next month, manuscript outline**

**Comment by kaizadp** [comment]
Aug 12, 2021
JZ, KFP

- what is the spatial distribution of SIDB, COSORE data?
- add data from NGEEs, SPRUCE and other similar networks?
    - [x] https://ngee-arctic.ornl.gov/data/ search for _Jianqiu_, _David Graham_
    - [ ] https://ngt-data.lbl.gov/dois/
    - [ ] https://mnspruce.ornl.gov
