### ISSUE TITLE
Comparing Q10 functions

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/field_lab_q10#14]
@jianqiuz I've written some script to fit Q10 functions. Need your help with the following:

### 1. goodness of fit
What index should we use to compare goodness of fit among models? There's no R-squared for non-linear models.
I found something [here](https://datascienceplus.com/first-steps-with-non-linear-regression-in-r/ ) that uses `cor()`. I'm using this for now, but we can modify if you have suggestions.

https://github.com/kaizadp/field_lab_q10/blob/1dad25f0d7a713370c4514d548c0da75a5814211/code/4-functions-q10_fitting.R#L88-L90

### 2. starting parameters for Arrhenius function
I need help creating code that will automatically choose starting parameters for a and Ea. Through trial and error, I was able to get starting parameters for one study (Andrews2000), but it doesn't work for all. 

https://github.com/kaizadp/field_lab_q10/blob/1dad25f0d7a713370c4514d548c0da75a5814211/code/4-functions-q10_fitting.R#L178-L182

Ben had set up something for the exponential fit, maybe we can do something similar for Arrhenius too? 👇🏽

https://github.com/kaizadp/field_lab_q10/blob/1dad25f0d7a713370c4514d548c0da75a5814211/code/4-functions-q10_fitting.R#L78-L81

### 3. filtering studies for quadratic fit
Some studies have only two temperature values, which fucks up the quadratic fit (need more than two unique values). For now, I've filtered those out from the entire calculation. But it would be good to include some kind of conditional code (loop?) such that if `distinct(temp) > 2` run the quadratic function, but if `distinct(temperatures) <= 2`, don't run quadratic but run the others. 

https://github.com/kaizadp/field_lab_q10/blob/1dad25f0d7a713370c4514d548c0da75a5814211/code/4-functions-q10_fitting.R#L217-L228

**Comment by jianqiuz** [comment]
This is the piece of code we discussed.

      obs <- nrow(sub_study)
        
        
        fit_a <- summary(curve.a)$coefficients[1,1] %>% round(6)
        fit_b <- summary(curve.b)$coefficients[1,1] %>% round(6)
        p_a <- summary(curve.a)$coefficients[1,4]%>% round(6)
        p_b <- summary(curve.b)$coefficients[1,4]%>% round(6)

        sub_study %>% mutate(yan_pred, yan_res) -> sub_study
        yan_RMSE <- (sum(sub_study$yan_res^2) / obs)^0.5 %>% round(3)
        yan_d <- (1- sum(sub_study$yan_res^2)/sum((sub_study$ra-mean(sub_study$ra))^2)) %>% round(3)
        
         
      lm_sum = data.frame(sub_study$id, sub_study$rs, sub_study$mvol,sub_study$porosity,sub_study$ra,sub_study$f_pred, sub_study$yan_pred,sub_study$yan_res,opt, fit_a, fit_b, p_a, p_b, yan_RMSE, yan_d)

**Comment by kaizadp** [comment]
@jianqiuz 
Thanks. What is `ra-mean` and `ra` in the code?

``` 
 yan_d <- (1- sum(sub_study$yan_res^2)/sum((sub_study$ra-mean(sub_study$ra))^2)) %>% round(3)
```

**Comment by jianqiuz** [comment]
"ra" is the observation value. 
You can try a few different functions, like MSE(mean square error), RMSE(Root mean squared error), RSS (residual sum of squares)

**Comment by kaizadp** [comment]
## 1. plotting the functions

@jianqiuz Do you have a better way of plotting the functions together? I had to do a weird roundabout way by creating a dummy dataset.

98a7b98


![image](https://user-images.githubusercontent.com/50244730/133855800-ba5ddef9-36f0-4520-b4ba-942ba48de75b.png)

---

## 2. time-series data

SIDB has data over multiple time points (different time scales for each experiment). I'm averaging across all time points.

![image](https://user-images.githubusercontent.com/50244730/133856510-8956c3f5-7401-4b2f-bc27-be3324cc5976.png)

---

## 3. fitting quadratic function

The quadratic function I've fit is giving me outrageous values for R10, etc. Need some help fitting this.

https://github.com/kaizadp/field_lab_q10/blob/98a7b985c8e955b9eb3c7b85847b04c7b7612573/code/4-functions-q10_fitting.R#L166-L185

![image](https://user-images.githubusercontent.com/50244730/133860177-100a2d9d-1e7d-4db8-953d-73e4d738d17e.png)

**Comment by kaizadp** [comment]
Time-series: cut off at 1-2 weeks, SIDB time is in days

**Comment by jianqiuz** [comment]
JZ---run scripts
KP--temperature unit (K), cut-off incubation time, save the summary table of fitting

**Comment by kaizadp** [comment]
@jianqiuz I tried using temp-K for quadratic, as discussed, but it made the R10/Q10 values worse. I checked in the literature, and they typically use Celsius for temperature anyway (example [here](https://doi.org/10.1073/pnas.1605365113)).

Could you run the script and see if you can fix?

**Comment by jianqiuz** [comment]
temp-K is for Arrhenius and ecosys (modified Arrhenius). Regression-based models like qadratic/linear should use temp-C

**Comment by kaizadp** [comment]
Ok, good to know. So that part is correct - the quadratic is using C, but still giving weird results. Could you check the code?
