### ISSUE TITLE
Standardizing ecosystem type

### ISSUE THREAD

**Issue by kaizadp** [kaizadp/field_lab_q10#15]
@bpbond 

I am trying to standardize the Ecosystem Type based on SRDB data. 
The data I have extracted from published papers are all over the place, and I am recording the changes here. Unsure of some changes (marked here in bold), can you please confirm/suggest a better one?

I am mostly doing this for the CO2 data, not CH4 (too few data points for meaningful analysis). There will be some entries (e.g. lake, rice paddies), that do not fall neatly into the SRDB categories, but I will leave those as is because of no CO2 data for those.

``` 
> srdb_q10 %>% distinct(Ecosystem_type)

  Ecosystem_type
1         Forest
2      Grassland
3      Shrubland
4    Agriculture
5        Savanna
6        Wetland
7         Desert
8           Bare
9         Tundra
```

CO2 file
- Cropland -> Agriculture
- **Cultivated -> Agriculture???**
- fen -> Wetland
- Forest
- Grass -> grassland
- Grassland
- NA
- Peat -> Wetland
- Peatland -> Wetland
- Polar desert -> Desert
- Tundra
- Wetland

CH4 file
- Agricultural -> agriculture 
- Agriculture
- Bog -> wetland
- Coastal fen -> wetland
- Fen -> wetland
- forest
- Kinosheo lake (ignore, because CH4 only)
- lake (ignore, because CH4 only)
- **Meadow -> Shrubland???**
- Minerotrophic peat -> wetland
- Mire -> wetland
- Peat -> wetland
- Peat bog -> wetland
- Peatland -> wetland
- Peatlands -> wetland
- **Permafrost -> tundra???**
- Prairie wetland -> wetland
- **Rice field** (ignore, because CH4 only)
- **Rice paddies** (ignore, because CH4 only)
- Subarctic tundra -> tundra
- Swamp -> wetland
- **Swamp meadow -> meadow or wetland???**
- **Tidal flat** (ignore, because CH4 only)
- Tropical forest -> forest
- Tropical peatland -> wetland
- Wet tundra -> tundra
- Wetland

**Comment by bpbond** [comment]
>Cultivated -> Agriculture???

Yes, agreed.

>Meadow -> Shrubland???

Yeah, not sure here. I think I'd usually record that as "Grassland". Ugh.

>Swamp meadow -> meadow or wetland???

Probably wetland?
